[tools]
elixir = "latest"
erlang = "latest"
# go = "1.26.5"

# "go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "v2.12.2"
# "go:golang.org/x/tools/gopls" = "v.0.23.0"
# "go:mvdan.cc/gofumpt" = "latest"
# "go:github.com/jesseduffield/lazygit" = "latest"
# "go:github.com/junegunn/fzf" = "latest"
# "go:honnef.co/go/tools/cmd/staticcheck" = "latest"

"cargo:bat" = "latest"
"cargo:git-delta" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:fnm" = "latest"
"cargo:just" = "latest"
"cargo:ripgrep" = "latest"
"cargo:starship" = "latest"
"cargo:tree-sitter-cli" = "latest"
"cargo:uv" = "latest"
"cargo:zellij" = "latest"
"cargo:zoxide" = "latest"
