[settings]
all_compile = true

[tools]
elixir = "latest"
erlang = "latest"
go = "latest"
zig = "latest"
zls = "latest"

"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"
"go:github.com/junegunn/fzf" = "latest"
"go:honnef.co/go/tools/cmd/staticcheck" = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"

"cargo:alacritty" = "latest"
"cargo:bat" = "latest"
"cargo:git-delta" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:fnm" = "latest"
"cargo:just" = "latest"
"cargo:ripgrep" = "latest"
"cargo:starship" = "latest"
"cargo:tree-sitter-cli" = "latest"
"cargo:uv" = "latest"
"cargo:zellij" = "latest"
"cargo:zoxide" = "latest"
