
[window]
opacity = 0.9
blur = true

[env]
TERM = "xterm-256color"

[general]
import = [
  "/home/acampbell/.config/alacritty/font.toml",
  "/home/acampbell/.config/alacritty/catppuccin-mocha.toml"
  # Available themes:
  # "/home/acampbell/.config/alacritty/onedark.toml"
  #  "/home/acampbell/.config/alacritty/catppuccin-macchiato.toml"
]

