#!/bin/bash
export VK_DRIVER_FILES=/usr/share/vulkan/icd.d/nvidia_icd.json
export __NV_PRIME_RENDER_OFFLOAD=1
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __VK_LAYER_NV_optimus=NVIDIA_only
export MESA_VK_DEVICE_SELECT=10de:1c8d

exec "$@" \
    --ignore-gpu-blocklist \
    --enable-features=Vulkan,VulkanFromANGLE,DefaultANGLEVulkan \
    --use-angle=vulkan \
    --disable-gpu-sandbox \
    --enable-gpu-rasterization
